// src/renderer/src/presentation/pages/PeopleManager/constants/index.ts

export const GENDER_OPTIONS = {
  MALE: 'male',
  FEMALE: 'female',
  OTHER: 'other'
} as const

export const IDENTIFICATION_TYPES = {
  PASSPORT: 'passport',
  NATIONAL_ID: 'national_id',
  DRIVER_LICENSE: 'driver_license',
  BIRTH_CERTIFICATE: 'birth_certificate'
} as const

export const CONTACT_TYPES = {
  PHONE: 'phone',
  EMAIL: 'email',
  FAX: 'fax',
  OTHER: 'other'
} as const

export const EMPLOYMENT_TYPES = {
  FULL_TIME: 'full_time',
  PART_TIME: 'part_time',
  CONTRACT: 'contract',
  INTERNSHIP: 'internship',
  FREELANCE: 'freelance',
  SELF_EMPLOYED: 'self_employed'
} as const

export const EVENT_TYPES = {
  MILESTONE: 'milestone',
  ACHIEVEMENT: 'achievement',
  CRISIS: 'crisis',
  CELEBRATION: 'celebration',
  LOSS: 'loss',
  CHANGE: 'change',
  OTHER: 'other'
} as const

export const HABIT_TYPES = {
  HEALTH: 'health',
  PRODUCTIVITY: 'productivity',
  SOCIAL: 'social',
  PERSONAL: 'personal',
  PROFESSIONAL: 'professional',
  OTHER: 'other'
} as const

export const HABIT_FREQUENCY = {
  DAILY: 'daily',
  WEEKLY: 'weekly',
  MONTHLY: 'monthly',
  IRREGULAR: 'irregular'
} as const

export const DOCUMENT_TYPES = {
  MEDICAL: 'medical',
  LEGAL: 'legal',
  FINANCIAL: 'financial',
  EDUCATIONAL: 'educational',
  PERSONAL: 'personal',
  OTHER: 'other'
} as const

export const IMPACT_LEVELS = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high'
} as const

// Label mappings
export const GENDER_LABELS = {
  [GENDER_OPTIONS.MALE]: 'Male',
  [GENDER_OPTIONS.FEMALE]: 'Female',
  [GENDER_OPTIONS.OTHER]: 'Other'
} as const

export const IDENTIFICATION_TYPE_LABELS = {
  [IDENTIFICATION_TYPES.PASSPORT]: 'Passport',
  [IDENTIFICATION_TYPES.NATIONAL_ID]: 'National ID',
  [IDENTIFICATION_TYPES.DRIVER_LICENSE]: 'Driver License',
  [IDENTIFICATION_TYPES.BIRTH_CERTIFICATE]: 'Birth Certificate'
} as const

export const CONTACT_TYPE_LABELS = {
  [CONTACT_TYPES.PHONE]: 'Phone',
  [CONTACT_TYPES.EMAIL]: 'Email',
  [CONTACT_TYPES.FAX]: 'Fax',
  [CONTACT_TYPES.OTHER]: 'Other'
} as const

export const EMPLOYMENT_TYPE_LABELS = {
  [EMPLOYMENT_TYPES.FULL_TIME]: 'Full Time',
  [EMPLOYMENT_TYPES.PART_TIME]: 'Part Time',
  [EMPLOYMENT_TYPES.CONTRACT]: 'Contract',
  [EMPLOYMENT_TYPES.INTERNSHIP]: 'Internship',
  [EMPLOYMENT_TYPES.FREELANCE]: 'Freelance',
  [EMPLOYMENT_TYPES.SELF_EMPLOYED]: 'Self Employed'
} as const

export const EVENT_TYPE_LABELS = {
  [EVENT_TYPES.MILESTONE]: 'Milestone',
  [EVENT_TYPES.ACHIEVEMENT]: 'Achievement',
  [EVENT_TYPES.CRISIS]: 'Crisis',
  [EVENT_TYPES.CELEBRATION]: 'Celebration',
  [EVENT_TYPES.LOSS]: 'Loss',
  [EVENT_TYPES.CHANGE]: 'Change',
  [EVENT_TYPES.OTHER]: 'Other'
} as const

export const HABIT_TYPE_LABELS = {
  [HABIT_TYPES.HEALTH]: 'Health',
  [HABIT_TYPES.PRODUCTIVITY]: 'Productivity',
  [HABIT_TYPES.SOCIAL]: 'Social',
  [HABIT_TYPES.PERSONAL]: 'Personal',
  [HABIT_TYPES.PROFESSIONAL]: 'Professional',
  [HABIT_TYPES.OTHER]: 'Other'
} as const

export const HABIT_FREQUENCY_LABELS = {
  [HABIT_FREQUENCY.DAILY]: 'Daily',
  [HABIT_FREQUENCY.WEEKLY]: 'Weekly',
  [HABIT_FREQUENCY.MONTHLY]: 'Monthly',
  [HABIT_FREQUENCY.IRREGULAR]: 'Irregular'
} as const

export const DOCUMENT_TYPE_LABELS = {
  [DOCUMENT_TYPES.MEDICAL]: 'Medical',
  [DOCUMENT_TYPES.LEGAL]: 'Legal',
  [DOCUMENT_TYPES.FINANCIAL]: 'Financial',
  [DOCUMENT_TYPES.EDUCATIONAL]: 'Educational',
  [DOCUMENT_TYPES.PERSONAL]: 'Personal',
  [DOCUMENT_TYPES.OTHER]: 'Other'
} as const

export const IMPACT_LEVEL_LABELS = {
  [IMPACT_LEVELS.LOW]: 'Low',
  [IMPACT_LEVELS.MEDIUM]: 'Medium',
  [IMPACT_LEVELS.HIGH]: 'High'
} as const

export const DATABASE_CONFIG = {
  FILE_EXTENSIONS: ['db', 'sqlite'],
  DEFAULT_NAME: 'people_manager.db',
  SUPPORTED_FORMATS: [
    { name: 'Database Files', extensions: ['db', 'sqlite'] },
    { name: 'All Files', extensions: ['*'] }
  ]
} as const

// Common countries list
export const COUNTRIES = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Lucia',
  'Samoa',
  'San Marino',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe'
]

// Mapping from nationality value to phone code
export const NATIONALITY_PHONE_CODES: Record<string, string> = {
  afghan: '+93',
  albanian: '+355',
  algerian: '+213',
  american: '+1',
  andorran: '+376',
  angolan: '+244',
  antiguans: '+1-268',
  argentinean: '+54',
  armenian: '+374',
  australian: '+61',
  austrian: '+43',
  azerbaijani: '+994',
  bahamian: '+1-242',
  bahraini: '+973',
  bangladeshi: '+880',
  barbadian: '+1-246',
  barbudans: '+1-268',
  batswana: '+267',
  belarusian: '+375',
  belgian: '+32',
  belizean: '+501',
  beninese: '+229',
  bhutanese: '+975',
  bolivian: '+591',
  bosnian: '+387',
  brazilian: '+55',
  british: '+44',
  bruneian: '+673',
  bulgarian: '+359',
  burkinabe: '+226',
  burmese: '+95',
  burundian: '+257',
  cambodian: '+855',
  cameroonian: '+237',
  canadian: '+1',
  cape_verdean: '+238',
  central_african: '+236',
  chadian: '+235',
  chilean: '+56',
  chinese: '+86',
  colombian: '+57',
  comoran: '+269',
  congolese: '+242',
  costa_rican: '+506',
  croatian: '+385',
  cuban: '+53',
  cypriot: '+357',
  czech: '+420',
  danish: '+45',
  djibouti: '+253',
  dominican: '+1-809',
  dutch: '+31',
  east_timorese: '+670',
  ecuadorean: '+593',
  egyptian: '+20',
  emirian: '+971',
  equatorial_guinean: '+240',
  eritrean: '+291',
  estonian: '+372',
  ethiopian: '+251',
  fijian: '+679',
  filipino: '+63',
  finnish: '+358',
  french: '+33',
  gabonese: '+241',
  gambian: '+220',
  georgian: '+995',
  german: '+49',
  ghanaian: '+233',
  greek: '+30',
  grenadian: '+1-473',
  guatemalan: '+502',
  guinea_bissauan: '+245',
  guinean: '+224',
  guyanese: '+592',
  haitian: '+509',
  herzegovinian: '+387',
  honduran: '+504',
  hungarian: '+36',
  icelander: '+354',
  indian: '+91',
  indonesian: '+62',
  iranian: '+98',
  iraqi: '+964',
  irish: '+353',
  israeli: '+972',
  italian: '+39',
  ivorian: '+225',
  jamaican: '+1-876',
  japanese: '+81',
  jordanian: '+962',
  kazakhstani: '+7',
  kenyan: '+254',
  kittian_and_nevisian: '+1-869',
  kuwaiti: '+965',
  kyrgyz: '+996',
  laotian: '+856',
  latvian: '+371',
  lebanese: '+961',
  liberian: '+231',
  libyan: '+218',
  liechtensteiner: '+423',
  lithuanian: '+370',
  luxembourger: '+352',
  macedonian: '+389',
  malagasy: '+261',
  malawian: '+265',
  malaysian: '+60',
  maldivan: '+960',
  malian: '+223',
  maltese: '+356',
  marshallese: '+692',
  mauritanian: '+222',
  mauritian: '+230',
  mexican: '+52',
  micronesian: '+691',
  moldovan: '+373',
  monacan: '+377',
  mongolian: '+976',
  moroccan: '+212',
  mosotho: '+266',
  motswana: '+267',
  mozambican: '+258',
  namibian: '+264',
  nauruan: '+674',
  nepalese: '+977',
  new_zealander: '+64',
  ni_vanuatu: '+678',
  nicaraguan: '+505',
  nigerien: '+227',
  north_korean: '+850',
  northern_irish: '+44',
  norwegian: '+47',
  omani: '+968',
  pakistani: '+92',
  palauan: '+680',
  panamanian: '+507',
  papua_new_guinean: '+675',
  paraguayan: '+595',
  peruvian: '+51',
  polish: '+48',
  portuguese: '+351',
  qatari: '+974',
  romanian: '+40',
  russian: '+7',
  rwandan: '+250',
  saint_lucian: '+1-758',
  salvadoran: '+503',
  samoan: '+685',
  san_marinese: '+378',
  sao_tomean: '+239',
  saudi: '+966',
  scottish: '+44',
  senegalese: '+221',
  serbian: '+381',
  seychellois: '+248',
  sierra_leonean: '+232',
  singaporean: '+65',
  slovakian: '+421',
  slovenian: '+386',
  solomon_islander: '+677',
  somali: '+252',
  south_african: '+27',
  south_korean: '+82',
  spanish: '+34',
  sri_lankan: '+94',
  sudanese: '+249',
  surinamer: '+597',
  swazi: '+268',
  swedish: '+46',
  swiss: '+41',
  syrian: '+963',
  taiwanese: '+886',
  tajik: '+992',
  tanzanian: '+255',
  thai: '+66',
  togolese: '+228',
  tongan: '+676',
  trinidadian_or_tobagonian: '+1-868',
  tunisian: '+216',
  turkish: '+90',
  tuvaluan: '+688',
  ugandan: '+256',
  ukrainian: '+380',
  uruguayan: '+598',
  uzbekistani: '+998',
  venezuelan: '+58',
  vietnamese: '+84',
  welsh: '+44',
  yemenite: '+967',
  zambian: '+260',
  zimbabwean: '+263'
}

// Update helper function
export const getPhoneCodeByNationality = (nationality: string): string => {
  return NATIONALITY_PHONE_CODES[nationality] || '+1'
}
