import type { LocaleInfo, OsTemplate, BrowserTemplate } from '../types/fingerprint-generator';

import type { LocaleInfo, OsTemplate, BrowserTemplate } from '../types/fingerprint-generator';

// ── Country → locale mapping ─────────────────────────────────────────
export const COUNTRY_LOCALE_MAP: Record<string, LocaleInfo> = {
  VN: {
    language: 'vi-VN',
    languages: ['vi-VN', 'vi', 'en-US', 'en'],
    timezones: ['Asia/Ho_Chi_Minh', 'Asia/Bangkok'],
    region: 'asia',
  },
  US: {
    language: 'en-US',
    languages: ['en-US', 'en'],
    timezones: ['America/New_York', 'America/Chicago', 'America/Los_Angeles', 'America/Denver'],
    region: 'north_america',
  },
  GB: {
    language: 'en-GB',
    languages: ['en-GB', 'en-US', 'en'],
    timezones: ['Europe/London'],
    region: 'europe',
  },
  DE: {
    language: 'de-DE',
    languages: ['de-DE', 'de', 'en-US', 'en'],
    timezones: ['Europe/Berlin'],
    region: 'europe',
  },
  FR: {
    language: 'fr-FR',
    languages: ['fr-FR', 'fr', 'en-US', 'en'],
    timezones: ['Europe/Paris'],
    region: 'europe',
  },
  JP: {
    language: 'ja-JP',
    languages: ['ja-JP', 'ja', 'en-US', 'en'],
    timezones: ['Asia/Tokyo'],
    region: 'asia',
  },
  KR: {
    language: 'ko-KR',
    languages: ['ko-KR', 'ko', 'en-US', 'en'],
    timezones: ['Asia/Seoul'],
    region: 'asia',
  },
  CN: {
    language: 'zh-CN',
    languages: ['zh-CN', 'zh', 'en-US', 'en'],
    timezones: ['Asia/Shanghai'],
    region: 'asia',
  },
  IN: {
    language: 'en-IN',
    languages: ['en-IN', 'hi-IN', 'en-US', 'en'],
    timezones: ['Asia/Kolkata'],
    region: 'asia',
  },
  BR: {
    language: 'pt-BR',
    languages: ['pt-BR', 'pt', 'en-US', 'en'],
    timezones: ['America/Sao_Paulo', 'America/Fortaleza'],
    region: 'south_america',
  },
  RU: {
    language: 'ru-RU',
    languages: ['ru-RU', 'ru', 'en-US', 'en'],
    timezones: ['Europe/Moscow'],
    region: 'europe',
  },
  TH: {
    language: 'th-TH',
    languages: ['th-TH', 'th', 'en-US', 'en'],
    timezones: ['Asia/Bangkok'],
    region: 'asia',
  },
  ID: {
    language: 'id-ID',
    languages: ['id-ID', 'id', 'en-US', 'en'],
    timezones: ['Asia/Jakarta'],
    region: 'asia',
  },
  PH: {
    language: 'en-PH',
    languages: ['en-PH', 'fil-PH', 'en-US', 'en'],
    timezones: ['Asia/Manila'],
    region: 'asia',
  },
  MY: {
    language: 'en-MY',
    languages: ['en-MY', 'ms-MY', 'en-US', 'en'],
    timezones: ['Asia/Kuala_Lumpur'],
    region: 'asia',
  },
  SG: {
    language: 'en-SG',
    languages: ['en-SG', 'zh-SG', 'en-US', 'en'],
    timezones: ['Asia/Singapore'],
    region: 'asia',
  },
  AU: {
    language: 'en-AU',
    languages: ['en-AU', 'en-US', 'en'],
    timezones: ['Australia/Sydney', 'Australia/Melbourne'],
    region: 'oceania',
  },
  CA: {
    language: 'en-CA',
    languages: ['en-CA', 'fr-CA', 'en-US', 'en'],
    timezones: ['America/Toronto', 'America/Vancouver'],
    region: 'north_america',
  },
  MX: {
    language: 'es-MX',
    languages: ['es-MX', 'es', 'en-US', 'en'],
    timezones: ['America/Mexico_City'],
    region: 'north_america',
  },
  AR: {
    language: 'es-AR',
    languages: ['es-AR', 'es', 'en-US', 'en'],
    timezones: ['America/Argentina/Buenos_Aires'],
    region: 'south_america',
  },
  ZA: {
    language: 'en-ZA',
    languages: ['en-ZA', 'af', 'en-US', 'en'],
    timezones: ['Africa/Johannesburg'],
    region: 'africa',
  },
  NG: {
    language: 'en-NG',
    languages: ['en-NG', 'ha', 'yo', 'en-US', 'en'],
    timezones: ['Africa/Lagos'],
    region: 'africa',
  },
  EG: {
    language: 'ar-EG',
    languages: ['ar-EG', 'ar', 'en-US', 'en'],
    timezones: ['Africa/Cairo'],
    region: 'africa',
  },
  SA: {
    language: 'ar-SA',
    languages: ['ar-SA', 'ar', 'en-US', 'en'],
    timezones: ['Asia/Riyadh'],
    region: 'middle_east',
  },
  AE: {
    language: 'ar-AE',
    languages: ['ar-AE', 'ar', 'en-US', 'en'],
    timezones: ['Asia/Dubai'],
    region: 'middle_east',
  },
  TR: {
    language: 'tr-TR',
    languages: ['tr-TR', 'tr', 'en-US', 'en'],
    timezones: ['Europe/Istanbul'],
    region: 'europe',
  },
  PL: {
    language: 'pl-PL',
    languages: ['pl-PL', 'pl', 'en-US', 'en'],
    timezones: ['Europe/Warsaw'],
    region: 'europe',
  },
  IT: {
    language: 'it-IT',
    languages: ['it-IT', 'it', 'en-US', 'en'],
    timezones: ['Europe/Rome'],
    region: 'europe',
  },
  ES: {
    language: 'es-ES',
    languages: ['es-ES', 'es', 'en-US', 'en'],
    timezones: ['Europe/Madrid'],
    region: 'europe',
  },
  NL: {
    language: 'nl-NL',
    languages: ['nl-NL', 'nl', 'en-US', 'en'],
    timezones: ['Europe/Amsterdam'],
    region: 'europe',
  },
  SE: {
    language: 'sv-SE',
    languages: ['sv-SE', 'sv', 'en-US', 'en'],
    timezones: ['Europe/Stockholm'],
    region: 'europe',
  },
  NO: {
    language: 'nb-NO',
    languages: ['nb-NO', 'nb', 'en-US', 'en'],
    timezones: ['Europe/Oslo'],
    region: 'europe',
  },
  DK: {
    language: 'da-DK',
    languages: ['da-DK', 'da', 'en-US', 'en'],
    timezones: ['Europe/Copenhagen'],
    region: 'europe',
  },
  FI: {
    language: 'fi-FI',
    languages: ['fi-FI', 'fi', 'en-US', 'en'],
    timezones: ['Europe/Helsinki'],
    region: 'europe',
  },
  PT: {
    language: 'pt-PT',
    languages: ['pt-PT', 'pt', 'en-US', 'en'],
    timezones: ['Europe/Lisbon'],
    region: 'europe',
  },
  GR: {
    language: 'el-GR',
    languages: ['el-GR', 'el', 'en-US', 'en'],
    timezones: ['Europe/Athens'],
    region: 'europe',
  },
  CZ: {
    language: 'cs-CZ',
    languages: ['cs-CZ', 'cs', 'en-US', 'en'],
    timezones: ['Europe/Prague'],
    region: 'europe',
  },
  RO: {
    language: 'ro-RO',
    languages: ['ro-RO', 'ro', 'en-US', 'en'],
    timezones: ['Europe/Bucharest'],
    region: 'europe',
  },
  HU: {
    language: 'hu-HU',
    languages: ['hu-HU', 'hu', 'en-US', 'en'],
    timezones: ['Europe/Budapest'],
    region: 'europe',
  },
  BG: {
    language: 'bg-BG',
    languages: ['bg-BG', 'bg', 'en-US', 'en'],
    timezones: ['Europe/Sofia'],
    region: 'europe',
  },
  UA: {
    language: 'uk-UA',
    languages: ['uk-UA', 'uk', 'ru', 'en-US', 'en'],
    timezones: ['Europe/Kiev'],
    region: 'europe',
  },
  KZ: {
    language: 'kk-KZ',
    languages: ['kk-KZ', 'ru', 'en-US', 'en'],
    timezones: ['Asia/Almaty'],
    region: 'asia',
  },
  UZ: {
    language: 'uz-UZ',
    languages: ['uz-UZ', 'ru', 'en-US', 'en'],
    timezones: ['Asia/Tashkent'],
    region: 'asia',
  },
  IR: {
    language: 'fa-IR',
    languages: ['fa-IR', 'fa', 'en-US', 'en'],
    timezones: ['Asia/Tehran'],
    region: 'middle_east',
  },
  IQ: {
    language: 'ar-IQ',
    languages: ['ar-IQ', 'ar', 'en-US', 'en'],
    timezones: ['Asia/Baghdad'],
    region: 'middle_east',
  },
  IL: {
    language: 'he-IL',
    languages: ['he-IL', 'he', 'en-US', 'en'],
    timezones: ['Asia/Jerusalem'],
    region: 'middle_east',
  },
};

export const DEFAULT_LOCALE: LocaleInfo = {
  language: 'en-US',
  languages: ['en-US', 'en'],
  timezones: ['UTC'],
  region: 'global',
};

export function getLocaleInfo(countryCode: string): LocaleInfo {
  return COUNTRY_LOCALE_MAP[countryCode?.toUpperCase()] || DEFAULT_LOCALE;
}

// ── OS templates ─────────────────────────────────────────────────────
export const OS_TEMPLATES: OsTemplate[] = [
  // ── Windows Desktop (phổ thông) ──────────────────────────────────
  {
    label: 'Windows 11 (Intel UHD)',
    group: 'Windows',
    platform: 'Win32',
    oscpu: 'Windows NT 10.0; Win64; x64',
    platformVersion: '14.0.0',
    windowsNtVersion: '10.0',
    hardwareConcurrency: 8,
    deviceMemory: 16,
    maxTouchPoints: 0,
    isMobile: false,
    webglVendor: 'Google Inc. (Intel)',
    webglRenderer:
      'ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.100.9864)',
    vendor: 'Google Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Arial',
      'Calibri',
      'Cambria',
      'Comic Sans MS',
      'Consolas',
      'Courier New',
      'Georgia',
      'Impact',
      'Segoe UI',
      'Tahoma',
      'Times New Roman',
      'Trebuchet MS',
      'Verdana',
    ],
    screens: [
      { width: 1366, height: 768, availHeightOffset: 40, dpr: 1 },
      { width: 1920, height: 1080, availHeightOffset: 40, dpr: 1 },
      { width: 2560, height: 1440, availHeightOffset: 40, dpr: 1 },
    ],
    batteryCharging: true,
    batteryLevel: 0.95,
    regions: [
      'north_america',
      'europe',
      'asia',
      'oceania',
      'south_america',
      'africa',
      'middle_east',
      'global',
    ],
  },
  {
    label: 'Windows 10 (Intel HD 4000)',
    group: 'Windows',
    platform: 'Win32',
    oscpu: 'Windows NT 10.0; Win64; x64',
    platformVersion: '10.0.0',
    windowsNtVersion: '10.0',
    hardwareConcurrency: 4,
    deviceMemory: 8,
    maxTouchPoints: 0,
    isMobile: false,
    webglVendor: 'Google Inc. (Intel)',
    webglRenderer:
      'ANGLE (Intel, Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0, D3D11-10.18.10.4358)',
    vendor: 'Google Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Arial',
      'Arial Black',
      'Calibri',
      'Cambria',
      'Comic Sans MS',
      'Consolas',
      'Courier New',
      'Georgia',
      'Impact',
      'Lucida Console',
      'Microsoft Sans Serif',
      'Palatino Linotype',
      'Tahoma',
      'Times New Roman',
      'Trebuchet MS',
      'Verdana',
    ],
    screens: [
      { width: 1366, height: 768, availHeightOffset: 40, dpr: 1 },
      { width: 1920, height: 1080, availHeightOffset: 40, dpr: 1 },
    ],
    batteryCharging: false,
    batteryLevel: 0.8,
    regions: [
      'north_america',
      'europe',
      'asia',
      'oceania',
      'south_america',
      'africa',
      'middle_east',
      'global',
    ],
  },
  // ── Windows máy bàn cao cấp (gaming) ─────────────────────────────
  {
    label: 'Windows 11 (RTX 3060)',
    group: 'Windows',
    platform: 'Win32',
    oscpu: 'Windows NT 10.0; Win64; x64',
    platformVersion: '14.0.0',
    windowsNtVersion: '10.0',
    hardwareConcurrency: 16,
    deviceMemory: 32,
    maxTouchPoints: 0,
    isMobile: false,
    webglVendor: 'Google Inc. (NVIDIA)',
    webglRenderer:
      'ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11-31.0.15.3640)',
    vendor: 'Google Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Arial',
      'Calibri',
      'Cambria',
      'Comic Sans MS',
      'Consolas',
      'Courier New',
      'Georgia',
      'Impact',
      'Segoe UI',
      'Tahoma',
      'Times New Roman',
      'Trebuchet MS',
      'Verdana',
      'Webdings',
      'Wingdings',
    ],
    screens: [
      { width: 1920, height: 1080, availHeightOffset: 40, dpr: 1 },
      { width: 2560, height: 1440, availHeightOffset: 40, dpr: 1 },
      { width: 3840, height: 2160, availHeightOffset: 40, dpr: 1 },
    ],
    batteryCharging: true,
    batteryLevel: 1.0,
    regions: ['north_america', 'europe', 'oceania', 'asia'],
  },
  // ── macOS Desktop / MacBook ─────────────────────────────────────
  {
    label: 'MacBook Air M1 2020',
    group: 'macOS',
    platform: 'MacIntel',
    oscpu: 'Intel Mac OS X 10_15_7',
    platformVersion: '14.5.0',
    hardwareConcurrency: 8,
    deviceMemory: 8,
    maxTouchPoints: 0,
    isMobile: false,
    webglVendor: 'Apple Inc.',
    webglRenderer: 'ANGLE (Apple, Apple M1, OpenGL 4.1)',
    vendor: 'Apple Computer, Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Apple Color Emoji',
      'Arial',
      'Courier',
      'Courier New',
      'Geneva',
      'Georgia',
      'Helvetica',
      'Helvetica Neue',
      'Lucida Grande',
      'Menlo',
      'Monaco',
      'SF Pro',
      'Times',
      'Times New Roman',
      'Trebuchet MS',
      'Verdana',
    ],
    screens: [
      { width: 1440, height: 900, availHeightOffset: 40, dpr: 2 },
      { width: 1680, height: 1050, availHeightOffset: 40, dpr: 2 },
    ],
    batteryCharging: false,
    batteryLevel: 0.75,
    regions: ['north_america', 'europe', 'oceania', 'asia'],
  },
  {
    label: 'MacBook Pro 14" M3 2023',
    group: 'macOS',
    platform: 'MacIntel',
    oscpu: 'Intel Mac OS X 10_15_7',
    platformVersion: '15.0.0',
    hardwareConcurrency: 14,
    deviceMemory: 32,
    maxTouchPoints: 0,
    isMobile: false,
    webglVendor: 'Apple Inc.',
    webglRenderer: 'ANGLE (Apple, Apple M3 Max, OpenGL 4.1)',
    vendor: 'Apple Computer, Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Apple Color Emoji',
      'Apple SD Gothic Neo',
      'Arial',
      'Courier',
      'Courier New',
      'Geneva',
      'Georgia',
      'Helvetica',
      'Helvetica Neue',
      'Lucida Grande',
      'Menlo',
      'Monaco',
      'SF Pro',
      'Times',
      'Times New Roman',
      'Trebuchet MS',
      'Verdana',
    ],
    screens: [
      { width: 1512, height: 982, availHeightOffset: 40, dpr: 2 },
      { width: 2560, height: 1440, availHeightOffset: 40, dpr: 2 },
    ],
    batteryCharging: true,
    batteryLevel: 0.91,
    regions: ['north_america', 'europe', 'oceania'],
  },
  // ── Linux desktop ───────────────────────────────────────────────
  {
    label: 'Linux (Ubuntu 22.04)',
    group: 'Linux',
    platform: 'Linux x86_64',
    oscpu: 'Linux x86_64',
    platformVersion: '6.5.0',
    hardwareConcurrency: 4,
    deviceMemory: 8,
    maxTouchPoints: 0,
    isMobile: false,
    webglVendor: 'Google Inc. (Intel)',
    webglRenderer: 'ANGLE (Intel, Mesa Intel(R) UHD Graphics 620, OpenGL 4.6)',
    vendor: 'Google Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Arial',
      'Courier',
      'Courier New',
      'DejaVu Sans',
      'DejaVu Serif',
      'Georgia',
      'Liberation Sans',
      'Liberation Serif',
      'Times',
      'Times New Roman',
      'Ubuntu',
      'Verdana',
    ],
    screens: [
      { width: 1366, height: 768, availHeightOffset: 40, dpr: 1 },
      { width: 1920, height: 1080, availHeightOffset: 40, dpr: 1 },
    ],
    batteryCharging: false,
    batteryLevel: 1.0,
    regions: ['europe', 'north_america', 'asia', 'global'],
  },
  // ── Smartphone Android ──────────────────────────────────────────
  {
    label: 'Samsung Galaxy S23 (Adreno 730)',
    group: 'Android',
    platform: 'Linux armv8l',
    oscpu: 'Linux armv8l',
    platformVersion: '13.0.0',
    hardwareConcurrency: 8,
    deviceMemory: 8,
    maxTouchPoints: 5,
    isMobile: true,
    webglVendor: 'Qualcomm',
    webglRenderer: 'ANGLE (Qualcomm, Adreno (TM) 730, OpenGL ES 3.2)',
    vendor: 'Google Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: ['Arial', 'Courier', 'Courier New', 'Georgia', 'Roboto', 'Times New Roman', 'Verdana'],
    screens: [
      { width: 360, height: 800, availHeightOffset: 60, dpr: 3 },
      { width: 412, height: 915, availHeightOffset: 60, dpr: 3.5 },
    ],
    batteryCharging: false,
    batteryLevel: 0.72,
    regions: ['north_america', 'europe', 'asia', 'middle_east', 'global'],
  },
  {
    label: 'Google Pixel 7 (Mali-G710)',
    group: 'Android',
    platform: 'Linux armv8l',
    oscpu: 'Linux armv8l',
    platformVersion: '13.0.0',
    hardwareConcurrency: 8,
    deviceMemory: 8,
    maxTouchPoints: 5,
    isMobile: true,
    webglVendor: 'ARM',
    webglRenderer: 'ANGLE (ARM, Mali-G710, OpenGL ES 3.2)',
    vendor: 'Google Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: ['Arial', 'Courier', 'Courier New', 'Georgia', 'Roboto', 'Times New Roman', 'Verdana'],
    screens: [{ width: 412, height: 915, availHeightOffset: 60, dpr: 3.5 }],
    batteryCharging: false,
    batteryLevel: 0.68,
    regions: ['north_america', 'europe', 'asia'],
  },
  {
    label: 'Xiaomi Redmi Note 12 (Adreno 610)',
    group: 'Android',
    platform: 'Linux armv8l',
    oscpu: 'Linux armv8l',
    platformVersion: '11.0.0',
    hardwareConcurrency: 8,
    deviceMemory: 4,
    maxTouchPoints: 5,
    isMobile: true,
    webglVendor: 'Qualcomm',
    webglRenderer: 'ANGLE (Qualcomm, Adreno (TM) 610, OpenGL ES 3.2)',
    vendor: 'Google Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: ['Arial', 'Courier', 'Courier New', 'Georgia', 'Roboto', 'Times New Roman', 'Verdana'],
    screens: [{ width: 360, height: 780, availHeightOffset: 60, dpr: 2.75 }],
    batteryCharging: false,
    batteryLevel: 0.55,
    regions: ['asia', 'africa', 'south_america', 'middle_east', 'north_america'],
  },
  {
    label: 'Samsung Galaxy A14 (Mali-G57)',
    group: 'Android',
    platform: 'Linux armv8l',
    oscpu: 'Linux armv8l',
    platformVersion: '12.0.0',
    hardwareConcurrency: 8,
    deviceMemory: 4,
    maxTouchPoints: 5,
    isMobile: true,
    webglVendor: 'ARM',
    webglRenderer: 'ANGLE (ARM, Mali-G57, OpenGL ES 3.2)',
    vendor: 'Google Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: ['Arial', 'Courier', 'Courier New', 'Georgia', 'Roboto', 'Times New Roman', 'Verdana'],
    screens: [{ width: 360, height: 800, availHeightOffset: 60, dpr: 2 }],
    batteryCharging: true,
    batteryLevel: 0.8,
    regions: ['asia', 'africa', 'south_america', 'europe', 'north_america'],
  },
  // ── iPhone ──────────────────────────────────────────────────────
  {
    label: 'iPhone 15 Pro (A17 Pro)',
    group: 'iOS',
    platform: 'iPhone',
    oscpu: 'CPU iPhone OS 17_0 like Mac OS X',
    platformVersion: '17.0.0',
    hardwareConcurrency: 6,
    deviceMemory: 8,
    maxTouchPoints: 5,
    isMobile: true,
    webglVendor: 'Apple Inc.',
    webglRenderer: 'ANGLE (Apple, Apple A17 Pro GPU, OpenGL ES 3.0)',
    vendor: 'Apple Computer, Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Academy Engraved LET',
      'American Typewriter',
      'Apple Color Emoji',
      'Arial',
      'Arial Hebrew',
      'Courier',
      'Courier New',
      'Georgia',
      'Helvetica',
      'Helvetica Neue',
      'Marker Felt',
      'Times New Roman',
      'Trebuchet MS',
      'Verdana',
      'Zapfino',
    ],
    screens: [
      { width: 393, height: 852, availHeightOffset: 60, dpr: 3 },
      { width: 430, height: 932, availHeightOffset: 60, dpr: 3 },
    ],
    batteryCharging: true,
    batteryLevel: 0.91,
    regions: ['north_america', 'europe', 'asia', 'oceania', 'middle_east'],
  },
  {
    label: 'iPhone 13 (A15)',
    group: 'iOS',
    platform: 'iPhone',
    oscpu: 'CPU iPhone OS 16_5 like Mac OS X',
    platformVersion: '16.5.0',
    hardwareConcurrency: 6,
    deviceMemory: 4,
    maxTouchPoints: 5,
    isMobile: true,
    webglVendor: 'Apple Inc.',
    webglRenderer: 'ANGLE (Apple, Apple A15 GPU, OpenGL ES 3.0)',
    vendor: 'Apple Computer, Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Academy Engraved LET',
      'American Typewriter',
      'Apple Color Emoji',
      'Arial',
      'Arial Hebrew',
      'Courier',
      'Courier New',
      'Georgia',
      'Helvetica',
      'Helvetica Neue',
      'Marker Felt',
      'Times New Roman',
      'Trebuchet MS',
      'Verdana',
    ],
    screens: [{ width: 390, height: 844, availHeightOffset: 60, dpr: 3 }],
    batteryCharging: false,
    batteryLevel: 0.65,
    regions: ['north_america', 'europe', 'asia', 'oceania', 'middle_east', 'south_america'],
  },
  {
    label: 'iPhone SE 2022 (A15)',
    group: 'iOS',
    platform: 'iPhone',
    oscpu: 'CPU iPhone OS 16_5 like Mac OS X',
    platformVersion: '16.5.0',
    hardwareConcurrency: 6,
    deviceMemory: 4,
    maxTouchPoints: 5,
    isMobile: true,
    webglVendor: 'Apple Inc.',
    webglRenderer: 'ANGLE (Apple, Apple A15 GPU, OpenGL ES 3.0)',
    vendor: 'Apple Computer, Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Academy Engraved LET',
      'American Typewriter',
      'Apple Color Emoji',
      'Arial',
      'Courier',
      'Courier New',
      'Georgia',
      'Helvetica',
      'Helvetica Neue',
      'Times New Roman',
      'Trebuchet MS',
      'Verdana',
    ],
    screens: [{ width: 375, height: 667, availHeightOffset: 60, dpr: 2 }],
    batteryCharging: false,
    batteryLevel: 0.55,
    regions: ['north_america', 'europe', 'asia', 'africa'],
  },
];

// ── Browser templates ────────────────────────────────────────────────
export const BROWSER_TEMPLATES: BrowserTemplate[] = [
  // Chrome
  {
    name: 'Chrome 143',
    brand: 'Google Chrome',
    brandVersion: '143',
    engineVersion: '143.0.0.0',
    appliesTo: 'all',
    userAgentTemplate: (os, cpu, v) =>
      `Mozilla/5.0 (${os}${cpu ? `; ${cpu}` : ''}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${v} Safari/537.36`,
  },
  {
    name: 'Chrome 140',
    brand: 'Google Chrome',
    brandVersion: '140',
    engineVersion: '140.0.0.0',
    appliesTo: 'all',
    userAgentTemplate: (os, cpu, v) =>
      `Mozilla/5.0 (${os}${cpu ? `; ${cpu}` : ''}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${v} Safari/537.36`,
  },
  {
    name: 'Chrome 130',
    brand: 'Google Chrome',
    brandVersion: '130',
    engineVersion: '130.0.0.0',
    appliesTo: 'all',
    userAgentTemplate: (os, cpu, v) =>
      `Mozilla/5.0 (${os}${cpu ? `; ${cpu}` : ''}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${v} Safari/537.36`,
  },
  // Firefox
  {
    name: 'Firefox 140',
    brand: 'Mozilla Firefox',
    brandVersion: '140',
    engineVersion: '140.0',
    appliesTo: 'desktop',
    userAgentTemplate: (os, _cpu, v) =>
      `Mozilla/5.0 (${os}; rv:${v}.0) Gecko/20100101 Firefox/${v}.0`,
  },
  {
    name: 'Firefox 130',
    brand: 'Mozilla Firefox',
    brandVersion: '130',
    engineVersion: '130.0',
    appliesTo: 'desktop',
    userAgentTemplate: (os, _cpu, v) =>
      `Mozilla/5.0 (${os}; rv:${v}.0) Gecko/20100101 Firefox/${v}.0`,
  },
  // Edge
  {
    name: 'Edge 143',
    brand: 'Microsoft Edge',
    brandVersion: '143',
    engineVersion: '143.0.0.0',
    appliesTo: 'desktop',
    onlyOnGroups: ['Windows', 'macOS'],
    userAgentTemplate: (os, cpu, v) =>
      `Mozilla/5.0 (${os}${cpu ? `; ${cpu}` : ''}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${v} Safari/537.36 Edg/${v}`,
  },
  {
    name: 'Edge 140',
    brand: 'Microsoft Edge',
    brandVersion: '140',
    engineVersion: '140.0.0.0',
    appliesTo: 'desktop',
    onlyOnGroups: ['Windows', 'macOS'],
    userAgentTemplate: (os, cpu, v) =>
      `Mozilla/5.0 (${os}${cpu ? `; ${cpu}` : ''}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${v} Safari/537.36 Edg/${v}`,
  },
  // Safari (chỉ macOS/iOS)
  {
    name: 'Safari 17',
    brand: 'Apple Safari',
    brandVersion: '17',
    engineVersion: '17.5',
    appliesTo: 'desktop',
    onlyOnGroups: ['macOS'],
    userAgentTemplate: (os, _cpu, _v) =>
      `Mozilla/5.0 (${os}) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15`,
  },
  {
    name: 'Safari 16',
    brand: 'Apple Safari',
    brandVersion: '16',
    engineVersion: '16.6',
    appliesTo: 'desktop',
    onlyOnGroups: ['macOS'],
    userAgentTemplate: (os, _cpu, _v) =>
      `Mozilla/5.0 (${os}) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15`,
  },
  {
    name: 'Mobile Safari 17',
    brand: 'Apple Safari',
    brandVersion: '17',
    engineVersion: '17.5',
    appliesTo: 'mobile',
    onlyOnGroups: ['iOS'],
    userAgentTemplate: (os, _cpu, _v) =>
      `Mozilla/5.0 (${os}) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1`,
  },
  // Opera
  {
    name: 'Opera 110',
    brand: 'Opera',
    brandVersion: '110',
    engineVersion: '110.0.0.0',
    appliesTo: 'desktop',
    userAgentTemplate: (os, cpu, v) =>
      `Mozilla/5.0 (${os}${cpu ? `; ${cpu}` : ''}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${v} Safari/537.36 OPR/${v}`,
  },
  // Samsung Internet (Android)
  {
    name: 'Samsung Internet 23',
    brand: 'Samsung Internet',
    brandVersion: '23',
    engineVersion: '115.0.0.0',
    appliesTo: 'mobile',
    onlyOnGroups: ['Android'],
    userAgentTemplate: (os, cpu, v) =>
      `Mozilla/5.0 (${os}${cpu ? `; ${cpu}` : ''}) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/23.0 Chrome/${v} Safari/537.36`,
  },
];