import type { OsTemplate } from './types';

export const OS_TEMPLATES: OsTemplate[] = [
  // ── Windows Desktop (phổ thông) ──────────────────────────────────
  {
    label: 'Windows 11 (Intel UHD)',
    group: 'Windows',
    platform: 'Win32',
    oscpu: 'Windows NT 10.0; Win64; x64',
    platformVersion: '14.0.0',
    windowsNtVersion: '10.0',
    hardwareConcurrency: 8,
    deviceMemory: 16,
    maxTouchPoints: 0,
    isMobile: false,
    webglVendor: 'Google Inc. (Intel)',
    webglRenderer:
      'ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.100.9864)',
    vendor: 'Google Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Arial',
      'Calibri',
      'Cambria',
      'Comic Sans MS',
      'Consolas',
      'Courier New',
      'Georgia',
      'Impact',
      'Segoe UI',
      'Tahoma',
      'Times New Roman',
      'Trebuchet MS',
      'Verdana',
    ],
    screens: [
      { width: 1366, height: 768, availHeightOffset: 40, dpr: 1 },
      { width: 1920, height: 1080, availHeightOffset: 40, dpr: 1 },
      { width: 2560, height: 1440, availHeightOffset: 40, dpr: 1 },
    ],
    batteryCharging: true,
    batteryLevel: 0.95,
    regions: [
      'north_america',
      'europe',
      'asia',
      'oceania',
      'south_america',
      'africa',
      'middle_east',
      'global',
    ],
  },
  {
    label: 'Windows 10 (Intel HD 4000)',
    group: 'Windows',
    platform: 'Win32',
    oscpu: 'Windows NT 10.0; Win64; x64',
    platformVersion: '10.0.0',
    windowsNtVersion: '10.0',
    hardwareConcurrency: 4,
    deviceMemory: 8,
    maxTouchPoints: 0,
    isMobile: false,
    webglVendor: 'Google Inc. (Intel)',
    webglRenderer:
      'ANGLE (Intel, Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0, D3D11-10.18.10.4358)',
    vendor: 'Google Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Arial',
      'Arial Black',
      'Calibri',
      'Cambria',
      'Comic Sans MS',
      'Consolas',
      'Courier New',
      'Georgia',
      'Impact',
      'Lucida Console',
      'Microsoft Sans Serif',
      'Palatino Linotype',
      'Tahoma',
      'Times New Roman',
      'Trebuchet MS',
      'Verdana',
    ],
    screens: [
      { width: 1366, height: 768, availHeightOffset: 40, dpr: 1 },
      { width: 1920, height: 1080, availHeightOffset: 40, dpr: 1 },
    ],
    batteryCharging: false,
    batteryLevel: 0.8,
    regions: [
      'north_america',
      'europe',
      'asia',
      'oceania',
      'south_america',
      'africa',
      'middle_east',
      'global',
    ],
  },
  // ── Windows máy bàn cao cấp (gaming) ─────────────────────────────
  {
    label: 'Windows 11 (RTX 3060)',
    group: 'Windows',
    platform: 'Win32',
    oscpu: 'Windows NT 10.0; Win64; x64',
    platformVersion: '14.0.0',
    windowsNtVersion: '10.0',
    hardwareConcurrency: 16,
    deviceMemory: 32,
    maxTouchPoints: 0,
    isMobile: false,
    webglVendor: 'Google Inc. (NVIDIA)',
    webglRenderer:
      'ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11-31.0.15.3640)',
    vendor: 'Google Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Arial',
      'Calibri',
      'Cambria',
      'Comic Sans MS',
      'Consolas',
      'Courier New',
      'Georgia',
      'Impact',
      'Segoe UI',
      'Tahoma',
      'Times New Roman',
      'Trebuchet MS',
      'Verdana',
      'Webdings',
      'Wingdings',
    ],
    screens: [
      { width: 1920, height: 1080, availHeightOffset: 40, dpr: 1 },
      { width: 2560, height: 1440, availHeightOffset: 40, dpr: 1 },
      { width: 3840, height: 2160, availHeightOffset: 40, dpr: 1 },
    ],
    batteryCharging: true,
    batteryLevel: 1.0,
    regions: ['north_america', 'europe', 'oceania', 'asia'],
  },
  // ── macOS Desktop / MacBook ─────────────────────────────────────
  {
    label: 'MacBook Air M1 2020',
    group: 'macOS',
    platform: 'MacIntel',
    oscpu: 'Intel Mac OS X 10_15_7',
    platformVersion: '14.5.0',
    hardwareConcurrency: 8,
    deviceMemory: 8,
    maxTouchPoints: 0,
    isMobile: false,
    webglVendor: 'Apple Inc.',
    webglRenderer: 'ANGLE (Apple, Apple M1, OpenGL 4.1)',
    vendor: 'Apple Computer, Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Apple Color Emoji',
      'Arial',
      'Courier',
      'Courier New',
      'Geneva',
      'Georgia',
      'Helvetica',
      'Helvetica Neue',
      'Lucida Grande',
      'Menlo',
      'Monaco',
      'SF Pro',
      'Times',
      'Times New Roman',
      'Trebuchet MS',
      'Verdana',
    ],
    screens: [
      { width: 1440, height: 900, availHeightOffset: 40, dpr: 2 },
      { width: 1680, height: 1050, availHeightOffset: 40, dpr: 2 },
    ],
    batteryCharging: false,
    batteryLevel: 0.75,
    regions: ['north_america', 'europe', 'oceania', 'asia'],
  },
  {
    label: 'MacBook Pro 14" M3 2023',
    group: 'macOS',
    platform: 'MacIntel',
    oscpu: 'Intel Mac OS X 10_15_7',
    platformVersion: '15.0.0',
    hardwareConcurrency: 14,
    deviceMemory: 32,
    maxTouchPoints: 0,
    isMobile: false,
    webglVendor: 'Apple Inc.',
    webglRenderer: 'ANGLE (Apple, Apple M3 Max, OpenGL 4.1)',
    vendor: 'Apple Computer, Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Apple Color Emoji',
      'Apple SD Gothic Neo',
      'Arial',
      'Courier',
      'Courier New',
      'Geneva',
      'Georgia',
      'Helvetica',
      'Helvetica Neue',
      'Lucida Grande',
      'Menlo',
      'Monaco',
      'SF Pro',
      'Times',
      'Times New Roman',
      'Trebuchet MS',
      'Verdana',
    ],
    screens: [
      { width: 1512, height: 982, availHeightOffset: 40, dpr: 2 },
      { width: 2560, height: 1440, availHeightOffset: 40, dpr: 2 },
    ],
    batteryCharging: true,
    batteryLevel: 0.91,
    regions: ['north_america', 'europe', 'oceania'],
  },
  // ── Linux desktop ───────────────────────────────────────────────
  {
    label: 'Linux (Ubuntu 22.04)',
    group: 'Linux',
    platform: 'Linux x86_64',
    oscpu: 'Linux x86_64',
    platformVersion: '6.5.0',
    hardwareConcurrency: 4,
    deviceMemory: 8,
    maxTouchPoints: 0,
    isMobile: false,
    webglVendor: 'Google Inc. (Intel)',
    webglRenderer: 'ANGLE (Intel, Mesa Intel(R) UHD Graphics 620, OpenGL 4.6)',
    vendor: 'Google Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Arial',
      'Courier',
      'Courier New',
      'DejaVu Sans',
      'DejaVu Serif',
      'Georgia',
      'Liberation Sans',
      'Liberation Serif',
      'Times',
      'Times New Roman',
      'Ubuntu',
      'Verdana',
    ],
    screens: [
      { width: 1366, height: 768, availHeightOffset: 40, dpr: 1 },
      { width: 1920, height: 1080, availHeightOffset: 40, dpr: 1 },
    ],
    batteryCharging: false,
    batteryLevel: 1.0,
    regions: ['europe', 'north_america', 'asia', 'global'],
  },
  // ── Smartphone Android ──────────────────────────────────────────
  {
    label: 'Samsung Galaxy S23 (Adreno 730)',
    group: 'Android',
    platform: 'Linux armv8l',
    oscpu: 'Linux armv8l',
    platformVersion: '13.0.0',
    hardwareConcurrency: 8,
    deviceMemory: 8,
    maxTouchPoints: 5,
    isMobile: true,
    webglVendor: 'Qualcomm',
    webglRenderer: 'ANGLE (Qualcomm, Adreno (TM) 730, OpenGL ES 3.2)',
    vendor: 'Google Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: ['Arial', 'Courier', 'Courier New', 'Georgia', 'Roboto', 'Times New Roman', 'Verdana'],
    screens: [
      { width: 360, height: 800, availHeightOffset: 60, dpr: 3 },
      { width: 412, height: 915, availHeightOffset: 60, dpr: 3.5 },
    ],
    batteryCharging: false,
    batteryLevel: 0.72,
    regions: ['north_america', 'europe', 'asia', 'middle_east', 'global'],
  },
  {
    label: 'Google Pixel 7 (Mali-G710)',
    group: 'Android',
    platform: 'Linux armv8l',
    oscpu: 'Linux armv8l',
    platformVersion: '13.0.0',
    hardwareConcurrency: 8,
    deviceMemory: 8,
    maxTouchPoints: 5,
    isMobile: true,
    webglVendor: 'ARM',
    webglRenderer: 'ANGLE (ARM, Mali-G710, OpenGL ES 3.2)',
    vendor: 'Google Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: ['Arial', 'Courier', 'Courier New', 'Georgia', 'Roboto', 'Times New Roman', 'Verdana'],
    screens: [{ width: 412, height: 915, availHeightOffset: 60, dpr: 3.5 }],
    batteryCharging: false,
    batteryLevel: 0.68,
    regions: ['north_america', 'europe', 'asia'],
  },
  {
    label: 'Xiaomi Redmi Note 12 (Adreno 610)',
    group: 'Android',
    platform: 'Linux armv8l',
    oscpu: 'Linux armv8l',
    platformVersion: '11.0.0',
    hardwareConcurrency: 8,
    deviceMemory: 4,
    maxTouchPoints: 5,
    isMobile: true,
    webglVendor: 'Qualcomm',
    webglRenderer: 'ANGLE (Qualcomm, Adreno (TM) 610, OpenGL ES 3.2)',
    vendor: 'Google Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: ['Arial', 'Courier', 'Courier New', 'Georgia', 'Roboto', 'Times New Roman', 'Verdana'],
    screens: [{ width: 360, height: 780, availHeightOffset: 60, dpr: 2.75 }],
    batteryCharging: false,
    batteryLevel: 0.55,
    regions: ['asia', 'africa', 'south_america', 'middle_east', 'north_america'],
  },
  {
    label: 'Samsung Galaxy A14 (Mali-G57)',
    group: 'Android',
    platform: 'Linux armv8l',
    oscpu: 'Linux armv8l',
    platformVersion: '12.0.0',
    hardwareConcurrency: 8,
    deviceMemory: 4,
    maxTouchPoints: 5,
    isMobile: true,
    webglVendor: 'ARM',
    webglRenderer: 'ANGLE (ARM, Mali-G57, OpenGL ES 3.2)',
    vendor: 'Google Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: ['Arial', 'Courier', 'Courier New', 'Georgia', 'Roboto', 'Times New Roman', 'Verdana'],
    screens: [{ width: 360, height: 800, availHeightOffset: 60, dpr: 2 }],
    batteryCharging: true,
    batteryLevel: 0.8,
    regions: ['asia', 'africa', 'south_america', 'europe', 'north_america'],
  },
  // ── iPhone ──────────────────────────────────────────────────────
  {
    label: 'iPhone 15 Pro (A17 Pro)',
    group: 'iOS',
    platform: 'iPhone',
    oscpu: 'CPU iPhone OS 17_0 like Mac OS X',
    platformVersion: '17.0.0',
    hardwareConcurrency: 6,
    deviceMemory: 8,
    maxTouchPoints: 5,
    isMobile: true,
    webglVendor: 'Apple Inc.',
    webglRenderer: 'ANGLE (Apple, Apple A17 Pro GPU, OpenGL ES 3.0)',
    vendor: 'Apple Computer, Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Academy Engraved LET',
      'American Typewriter',
      'Apple Color Emoji',
      'Arial',
      'Arial Hebrew',
      'Courier',
      'Courier New',
      'Georgia',
      'Helvetica',
      'Helvetica Neue',
      'Marker Felt',
      'Times New Roman',
      'Trebuchet MS',
      'Verdana',
      'Zapfino',
    ],
    screens: [
      { width: 393, height: 852, availHeightOffset: 60, dpr: 3 },
      { width: 430, height: 932, availHeightOffset: 60, dpr: 3 },
    ],
    batteryCharging: true,
    batteryLevel: 0.91,
    regions: ['north_america', 'europe', 'asia', 'oceania', 'middle_east'],
  },
  {
    label: 'iPhone 13 (A15)',
    group: 'iOS',
    platform: 'iPhone',
    oscpu: 'CPU iPhone OS 16_5 like Mac OS X',
    platformVersion: '16.5.0',
    hardwareConcurrency: 6,
    deviceMemory: 4,
    maxTouchPoints: 5,
    isMobile: true,
    webglVendor: 'Apple Inc.',
    webglRenderer: 'ANGLE (Apple, Apple A15 GPU, OpenGL ES 3.0)',
    vendor: 'Apple Computer, Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Academy Engraved LET',
      'American Typewriter',
      'Apple Color Emoji',
      'Arial',
      'Arial Hebrew',
      'Courier',
      'Courier New',
      'Georgia',
      'Helvetica',
      'Helvetica Neue',
      'Marker Felt',
      'Times New Roman',
      'Trebuchet MS',
      'Verdana',
    ],
    screens: [{ width: 390, height: 844, availHeightOffset: 60, dpr: 3 }],
    batteryCharging: false,
    batteryLevel: 0.65,
    regions: ['north_america', 'europe', 'asia', 'oceania', 'middle_east', 'south_america'],
  },
  {
    label: 'iPhone SE 2022 (A15)',
    group: 'iOS',
    platform: 'iPhone',
    oscpu: 'CPU iPhone OS 16_5 like Mac OS X',
    platformVersion: '16.5.0',
    hardwareConcurrency: 6,
    deviceMemory: 4,
    maxTouchPoints: 5,
    isMobile: true,
    webglVendor: 'Apple Inc.',
    webglRenderer: 'ANGLE (Apple, Apple A15 GPU, OpenGL ES 3.0)',
    vendor: 'Apple Computer, Inc.',
    vendorSub: '',
    productSub: '20030107',
    fonts: [
      'Academy Engraved LET',
      'American Typewriter',
      'Apple Color Emoji',
      'Arial',
      'Courier',
      'Courier New',
      'Georgia',
      'Helvetica',
      'Helvetica Neue',
      'Times New Roman',
      'Trebuchet MS',
      'Verdana',
    ],
    screens: [{ width: 375, height: 667, availHeightOffset: 60, dpr: 2 }],
    batteryCharging: false,
    batteryLevel: 0.55,
    regions: ['north_america', 'europe', 'asia', 'africa'],
  },
];